# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Movie.destroy_all

empire_strikes = Movie.create(name: "The Empire Strikes Back", genre: "Sci-Fi / Fantasy", year: 1980, synopsis: "The Empire Strikes Back (also known as Star Wars: Episode V – The Empire Strikes Back) is a 1980 American epic space opera film directed by Irvin Kershner. Leigh Brackett and Lawrence Kasdan wrote the screenplay, with George Lucas writing the film's story and serving as executive producer. The second installment in the original Star Wars trilogy, it was produced by Gary Kurtz for Lucasfilm and stars Mark Hamill, Harrison Ford, Carrie Fisher, Billy Dee Williams, Anthony Daniels, David Prowse, Kenny Baker, Peter Mayhew, and Frank Oz. The film is set three years after Star Wars. The Galactic Empire, under the leadership of the villainous Darth Vader and the mysterious Emperor, is in pursuit of Luke Skywalker and the rest of the Rebel Alliance. While Vader relentlessly pursues the small band of Luke's friends—Han Solo, Princess Leia Organa, and others—across the galaxy, Luke studies the Force under Jedi Master Yoda. When Vader captures Luke's friends, Luke must decide whether to complete his training and become a full Jedi Knight or to confront Vader and save them.", picture: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3c/SW_-_Empire_Strikes_Back.jpg/220px-SW_-_Empire_Strikes_Back.jpg", favorite: true)
blade_runner = Movie.create(name: "Blade Runner", genre: "Sci-Fi / Noir", year: 1982, synopsis: "In 2019 Los Angeles, former police officer Rick Deckard is detained by officer Gaff, and brought to his former supervisor, Bryant. Deckard, whose job as a 'blade runner' was to track down bioengineered beings known as replicants and 'retire' (kill) them, is informed that four are on Earth illegally. Deckard starts to leave, but Bryant ambiguously threatens him, and he stays. The two watch a video of a blade runner named Holden administering the 'Voigt-Kampff' test, which is designed to distinguish replicants from humans based on their emotional response to questions. The test subject, Leon, shoots Holden on the second question. Bryant wants Deckard to retire Leon and the other three Tyrell Corporation Nexus-6 replicants: Roy Batty, Zhora, and Pris.", picture: "https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Blade_Runner_poster.jpg/220px-Blade_Runner_poster.jpg", favorite: true)
seven = Movie.create(name: "Seven Samurai", genre: "Drama", year: 1954, synopsis: "Seven Samurai (七人の侍 Shichinin no Samurai) is a 1954 Japanese epic samurai drama film co-written, edited, and directed by Akira Kurosawa. The story takes place in 1586 during the Sengoku Period of Japanese history. It follows the story of a village of farmers that hire seven rōnin (masterless samurai) to combat bandits who will return after the harvest to steal their crops. Since its release, Seven Samurai has consistently ranked highly in critics' lists of the greatest films, such as the BFI's Sight & Sound and Rotten Tomatoes polls. It has remained highly influential, often seen as one of the most 'remade, reworked, referenced' films in cinema.", picture: "https://upload.wikimedia.org/wikipedia/en/thumb/8/84/Seven_Samurai_movie_poster.jpg/220px-Seven_Samurai_movie_poster.jpg", favorite: true)
